apiVersion: v1
kind: ServiceAccount
metadata:
  name: inserv
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inserv
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inserv
subjects:
  - kind: ServiceAccount
    name: inserv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: inserv

