apiVersion: v1
kind: Service
metadata:
  name: inorch-tmf-proxy
spec:
  selector:
    app: inorch-tmf-proxy
  ports:
    - port: 80
      targetPort: 3020
      protocol: TCP
      name: http
  type: ClusterIP

