{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "inserv.fullname" . }}
  namespace: {{ include "inserv.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "inserv.serviceAccountName" . }}
    namespace: {{ include "inserv.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "inserv.fullname" . }}
{{- end }}

