{{- if and .Values.openWebUI.enabled .Values.openWebUI.ingress.enabled }}
{{- $fullName := include "rusty-llm.fullname" . }}
{{- $svcPort := .Values.openWebUI.service.port }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-open-webui
  labels:
    {{- include "rusty-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: open-webui
  {{- with .Values.openWebUI.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.openWebUI.ingress.className }}
  ingressClassName: {{ .Values.openWebUI.ingress.className }}
  {{- end }}
  {{- if .Values.openWebUI.ingress.tls }}
  tls:
    {{- range .Values.openWebUI.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.openWebUI.ingress.hosts }}
    {{- if .host }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-open-webui-ext
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}-open-webui-ext
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}

