apiVersion: v1
kind: Service
metadata:
  name: {{ include "rusty-llm.fullname" . }}-ext
  labels:
    {{- include "rusty-llm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rusty-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rusty-llm.fullname" . }}
  labels:
    {{- include "rusty-llm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rusty-llm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ai-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
  type: ClusterIP

