{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "inorch-tmf-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "inorch-tmf-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "inorch-tmf-proxy.serviceAccountName" . }}
    namespace: {{ include "inorch-tmf-proxy.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "inorch-tmf-proxy.fullname" . }}
{{- end }}

