apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inorch-tmf-proxy.fullname" . }}-secret
  namespace: {{ include "inorch-tmf-proxy.namespace" . }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: "{{ $value }}"
{{- end }}

