{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inorch-tmf-proxy.serviceAccountName" . }}
  namespace: {{ include "inorch-tmf-proxy.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "inorch-tmf-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}

